-- FANCLUV — 0083: K리그 경기센터 실데이터(순위·일정·결과) 저장.
--
-- 소스: www.kleague.com 공식 (teamRank.do / getScheduleList.do) → league-fetcher Edge(서버 수집·정규화)
--        → 이 테이블 → 브라우저는 이 테이블만 읽는다(외부 직접 호출 0).
-- 원칙: additive. 쓰기는 service_role/RPC 만(브라우저 금지). 읽기는 공개(공용 스포츠 데이터).
--   dedup: matches UNIQUE(external_id), standings UNIQUE(season_id, team_code). 부분 실패로 전체 삭제 없음.
begin;

-- 시즌(§12 — 하드코딩 금지, is_current 로 현재 시즌 관리)
create table if not exists public.league_seasons (
  id          bigint generated by default as identity primary key,
  league_id   int  not null default 1,          -- 1=K리그1, 2=K리그2
  season_year int  not null,
  is_current  boolean not null default false,
  updated_at  timestamptz not null default now(),
  unique (league_id, season_year)
);

-- 순위표 (§15) — season 별 팀당 1행.
create table if not exists public.league_standings (
  id           bigint generated by default as identity primary key,
  season_id    bigint not null references public.league_seasons(id) on delete cascade,
  club_id      text,                             -- FANCLUV clubId(미매핑이면 null)
  team_code    text not null,                    -- 공식 팀코드(K09 등)
  team_name    text not null,
  rank         int not null,
  played       int not null default 0,
  wins         int not null default 0,
  draws        int not null default 0,
  losses       int not null default 0,
  goals_for    int not null default 0,
  goals_against int not null default 0,
  goal_difference int not null default 0,
  points       int not null default 0,
  form         text[] not null default '{}',
  updated_at   timestamptz not null default now(),
  unique (season_id, team_code)
);
create index if not exists league_standings_season_rank_idx on public.league_standings (season_id, rank);

-- 경기 일정/결과 (§16/§17) — external_id 로 dedup.
create table if not exists public.league_matches (
  id             bigint generated by default as identity primary key,
  external_id    text not null unique,           -- 공식 gameId
  league_id      int not null default 1,
  season_year    int not null,
  round          int,
  kickoff_at     timestamptz,                    -- KST 경기시각을 UTC 로 저장(§13)
  game_date      text,                           -- 원본 표기 보존(YYYY.MM.DD)
  game_time      text,
  home_club_id   text,
  away_club_id   text,
  home_code      text,
  away_code      text,
  home_team_name text,
  away_team_name text,
  home_score     int,                            -- finished 아니면 null
  away_score     int,
  status         text not null default 'scheduled'
                 check (status in ('scheduled','live','finished','postponed','cancelled')),
  stadium        text,
  updated_at     timestamptz not null default now()
);
create index if not exists league_matches_season_kick_idx on public.league_matches (league_id, season_year, kickoff_at);
create index if not exists league_matches_home_idx on public.league_matches (home_club_id, kickoff_at);
create index if not exists league_matches_away_idx on public.league_matches (away_club_id, kickoff_at);
create index if not exists league_matches_status_idx on public.league_matches (status, kickoff_at);

-- 수집 상태(§24 Source Health) — resource 별 1행.
create table if not exists public.league_sync_state (
  resource        text primary key,              -- 'standings' | 'matches'
  last_success_at timestamptz,
  last_error_at   timestamptz,
  last_error      text,
  last_rows       int,
  run_count       int not null default 0,
  fail_count      int not null default 0,
  updated_at      timestamptz not null default now()
);

-- ── RLS: 공개 읽기 / 브라우저 쓰기 금지(service_role 만 = RLS 우회) ──
alter table public.league_seasons   enable row level security;
alter table public.league_standings enable row level security;
alter table public.league_matches   enable row level security;
alter table public.league_sync_state enable row level security;
do $$ begin
  create policy "league_seasons public read"   on public.league_seasons   for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "league_standings public read" on public.league_standings for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "league_matches public read"   on public.league_matches   for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "league_sync public read"      on public.league_sync_state for select using (public.is_admin());
exception when duplicate_object then null; end $$;
-- (INSERT/UPDATE/DELETE 정책 없음 → service_role 만 쓰기)

-- ── 읽기 RPC (현재 시즌 자동 선택; 브라우저가 이것만 호출) ──
create or replace function public.league_current_season(p_league int default 1)
returns int language sql stable set search_path=public as $$
  select coalesce(
    (select season_year from public.league_seasons where league_id=p_league and is_current order by season_year desc limit 1),
    (select max(season_year) from public.league_seasons where league_id=p_league)
  )
$$;
grant execute on function public.league_current_season(int) to anon, authenticated;

create or replace function public.league_standings_view(p_league int default 1, p_year int default null)
returns jsonb language sql stable set search_path=public as $$
  with y as (select coalesce(p_year, public.league_current_season(p_league)) yr)
  select jsonb_build_object(
    'league', p_league, 'season', (select yr from y),
    'rows', coalesce(jsonb_agg(jsonb_build_object(
      'rank', s.rank, 'clubId', s.club_id, 'teamCode', s.team_code, 'teamName', s.team_name,
      'played', s.played, 'wins', s.wins, 'draws', s.draws, 'losses', s.losses,
      'goalsFor', s.goals_for, 'goalsAgainst', s.goals_against, 'goalDifference', s.goal_difference,
      'points', s.points, 'form', s.form
    ) order by s.rank), '[]'::jsonb),
    'updatedAt', max(s.updated_at)
  )
  from public.league_standings s
  join public.league_seasons se on se.id = s.season_id
  where se.league_id = p_league and se.season_year = (select yr from y)
$$;
grant execute on function public.league_standings_view(int, int) to anon, authenticated;

create or replace function public.league_matches_view(p_league int default 1, p_club text default null, p_year int default null)
returns jsonb language sql stable set search_path=public as $$
  with y as (select coalesce(p_year, public.league_current_season(p_league)) yr)
  select coalesce(jsonb_agg(jsonb_build_object(
      'externalId', m.external_id, 'round', m.round, 'kickoffAt', m.kickoff_at,
      'gameDate', m.game_date, 'gameTime', m.game_time,
      'homeClubId', m.home_club_id, 'awayClubId', m.away_club_id,
      'homeTeamName', m.home_team_name, 'awayTeamName', m.away_team_name,
      'homeScore', m.home_score, 'awayScore', m.away_score,
      'status', m.status, 'stadium', m.stadium
    ) order by m.kickoff_at), '[]'::jsonb)
  from public.league_matches m
  where m.league_id = p_league and m.season_year = (select yr from y)
    and (p_club is null or m.home_club_id = p_club or m.away_club_id = p_club)
$$;
grant execute on function public.league_matches_view(int, text, int) to anon, authenticated;

-- Source health(관리자용)
create or replace function public.league_sync_health()
returns jsonb language sql stable security definer set search_path=public as $$
  select case when not public.is_admin() then jsonb_build_object('ok', false, 'code','NOT_ALLOWED')
  else jsonb_build_object('ok', true,
    'season', (select public.league_current_season(1)),
    'standingsTeams', (select count(*) from public.league_standings s join public.league_seasons se on se.id=s.season_id where se.league_id=1 and se.season_year=public.league_current_season(1)),
    'matches', (select count(*) from public.league_matches where league_id=1 and season_year=public.league_current_season(1)),
    'sync', (select coalesce(jsonb_agg(jsonb_build_object('resource',resource,'lastSuccessAt',last_success_at,'lastErrorAt',last_error_at,'lastError',last_error,'lastRows',last_rows,'runCount',run_count,'failCount',fail_count) order by resource), '[]'::jsonb) from public.league_sync_state)
  ) end
$$;
grant execute on function public.league_sync_health() to authenticated;

commit;
